@document.meta
title: the Low-Canals Region
description: jagaranth lexicon entry
categories: [ conlang, lexicon, jagaranth, milieu ]
@end


* Jagaranth Intro

  - Jagaranth is a purely agglutinative language of the Jagarôth linguistic family.

* It is the language of the Low-Canals Region of Mars

  -  One of the more legendary locales in all of Galaxia, and the legendarium in
     question is replete with tales of crime, oppression, depression, adventure,
     and violence; also drug abuse abounds there, along with juvenile and adult
     delinquency, madness, dejection, abjection, prostution, religious mania,
     monomania; the people there perpetrate a gamut of addictions, heroisms,
     damnations and salvations.

  - The semiautonomous city of Jarthex dominates here a landscape of convergent
    canals, manufactoria, latifundia, and low small cities that are little more
    than heaps of hovels. The country is flat red sand and boulders, with low
    hills that vanish when the dust is up, and coppices of scrannel trees that
    clash with shiny blackish leaves.

  - A curious feature of Jagaranth and all the languages of the Jagarôth family
    is composability and construability, that is, the ability to combine
    morphemes with few limits other than intelligibility.

