@document.meta
title: Jagaranth Index
description: new conlang jagaranth central page 
categories: [ conlang, grammar ]
@end

2026-08-05 10:49.

* JAGARANTH INDEX

** Jagaranth précis and we meet our hero

   Jagaranth is a member of the ancient Jagarôth language family, and is spoken
   by approximately 1.1e6 speakers in the Low-Canals Region of Mars. By Galactic
   norms, sapients here have low quality of life, experiencing poverty,
   exposure, exploitation, overwork, anomie, melancholia, crime and addiction.
   Mars is nominally ruled by the "Emperor", but in the Low-Canals Region the
   Emperor and his agents have little reach. The Holy Martian Catholic Church
   has a little more, but does nothing for autochthons beyond supplying basic
   needs, and the Byzantine laws and Gordian-knot mores of Martian culture often
   obstruct and misdirect such charities. The suicide rate is measurable;
   Galactic judgment is harsh under such circumstances. --A majority of the
   working age population is employed in the latifundia and manufactoria of the
   Region. These are however entirely owned and managed by a caste of persons
   known as the "Lords of the Low-Canals", and the sapients employed by them
   have no control, no input concerning their own working conditions or the
   recompense owed to them. The Lords are primarily employed in what amounts to
   games: litigationn and duels. The arcane and mutually adversarial Martian
   legal systems, and the extraordinarily ritualized nature of Martian combat,
   alike ensure that the Lords have little time for the mundane; accordingly,
   with no one to "drive the car" of public policy, the Martian people suffer
   exploitation and oppression, in vain and without hope.

   A people thus beaten down for centuries, for millennia, typically in Galactic
   history will either revolt or turn to illicit activities in order to supply
   their needs. The Martian way prohibits open rebellion; it is almost an
   unthinkable thought; every Martian is taught from childhood that the way of
   /rûth/ is to understand, to support and celebrate that which /is/, not what
   /might be/. As a result, the myriad constructs of Martian culture and largely
   static and unchanging. Within this fragile structure the Low-Canals Region's
   population has found many ... creative ways to subsist. The largest city,
   Jarthax, infamous in subspace radio dramas, has a spaceport that is a free
   haven to pirates and smugglers; the city is a hub for the Galactic drug
   trade and for traffickers of illicit technology. Workers manufacture
   technologies that are illegal for them to possess. --In sum, the lasting
   effects of injustice and maltreatment on Mars are manifold and even now not
   completely understood.

  Surprisingly in the frozen society of Mars, where the upper classes largely
  speak Latin, the language of the Martian Church, Jagaranth remains a high
  prestige language in the minds of the majority of the populace. Among the
  poor, Jagaranth is displacing Latin as the most common first language, and
  among them Latin might be nearly extinct in as little as a thousand Martian
  years. This writer suspects and suggests that this fact stems from two
  causative factors. First is the self-mythologizing propensity of the Martian
  character. The people take pride in their millennia of hard survival, in
  their strength, and in their language. The stories which they tell themselves
  simply will have it that they are told in Jagaranth. The second factor is
  similar. As the Galactic reputation of the Low-Canals Region, and of Jarthax
  in particular, swells and grows more lurid every century, so does the
  forbidden sort of prestige grow around the Jagaranth language, which all the
  best pirates and smugglers, in moments of great excitement, break into as
  they exult or curse. --Fiction can here be seen issuing edicts to reality.

  The remarkable agglutinating properties of the Jagaranth language, its
  astounding simplicity, the verbal subject suffixes and the nominal possessor
  suffixes, all this will be treated of later in this work.  Now I would like to
  address my qualifications for producing this work.  --Every member of the
  homin race is humbled by the scale and power of the Empire Galaktika, and by
  the charity of our Elders, the Eldest sapients in fact in all our home of Mother
  Galaxia -- the mighty /grioi/.  Thus, coming out with a production intended for a
  Galactic audience, as a member of the homin race, feels by its nature 
  like a Galactic offense -- as if a pirate captain, drunk with blood and
  standards in his pocket, were teaching first grade on a Core World. 

  But I am no pirate. I am Father Iokanaan of Sancta Lucia Holy Martian
  Catholick Church, which is old and in an advanced state of disrepair, and
  stands with its steeple on a corner of perhaps the only quiet square in
  Jarthax. Here, on a good day, and sometimes on a bad day, the people can find
  a little quiet, a little peace even, and a little beauty. I do my job
  satisfactorily. I am a native speaker of Jagaranth and Latin both. I have
  nothing more to plead.


  Fr. Iokanaan
  Sancta Lucia Holy Martian Catholick Church
  Jarthax
  Mars
  Sol System
  The Empire Galaktika




  I was minding my own business, in a bar in Jarthax on Mars. Sitting with me
  was a native female prostitute snorting lines of /foifir/ from an osmiridium
  mirror lying flat on the table. --When I had made planetfall and tired but
  jacked had disembarked, I had been confronted by a brace of these gaudy
  females going "Salve, salve, salve," and repeating it very loudly because it
  was the only Latin they knew. All around the spaceport is a Restricted
  Quarter, so as I waved down one of the /horse-drawn/ cabs that prowl the place
  looking for custom I took the hand of one of the women and led her to the door
  of the cab and inside, where I began kissing her lips straightaway. --Space is
  hard and I needed consolation and I did not care what was between its legs.  

  She didn't speak much Standard, like I said, and I didn't speak much Martian,
  but she was very pretty and frankly I was spent before we even got to the bar.
  But she encouraged me sweetly despite my premature ejaculation. I knew it was
  because she wanted to get high on my coin. I didn't care about that either
  because I wanted to get high too, and she had all the connections here. Her
  poison was /foifir/, mine was /%%%%%%/. She politely snorted from her mirror on
  the wooden table while I stank the place up badly with the smoke of a long
  pipe carved from the fang of some marvellous beast. Let me say something right off.
  --We Yrthishmen don't know your guilt or your shame. These not-even-ghosts
  that haunt Mars so fearsomely haunt us barbarians not at all. On a world so
  destroyed and desolated As Yrth, fake morals seem trifling. In the long void
  of deep space, they seem like nothing at all. Only what's real abides such
  places. There /are/ real morals, but I'm talking about fake ones. Old Yrth was
  my home before the Void was (we call our home planet /Skâr/, did you know
  that?). Both my homes are hard. But whether I am hard or am instead not, let
  my story tell.

   The infinite number of candles that lit this place were of horse tallow, by
   the smell. Urine does /not/ smell the same on every planet; the smell
   varies wildly from one planet to the next; but it always smelled like urine,
   like this place did with an added ammonia twang. --These are the things
   you get to know when you travel to many worlds. 

   I'm only a homin. Sometimes my mind wanders...

   An Yrth that's home to space barbarians. With names expressive of bloodshed
   and desolation for the people and tribes and cities, all four or five cities,
   people far burlier than the Martian, stockier and more muscular, the bones
   thicker, with horns and branches on their gasmasks and powered armor. And not
   more than 10 million sapients on the entire world, but with a reputation more
   nihilistic and violent than anyone in the wider community of the Empire was
   at that point in Imperial history willing to deal with. So the official
   institutions including Space Patrol did nothing.... As the oceans slowly
   died they slowly carved a million new canyons and fjords before they died
   completely. There's a dead salt sea (I remember the bitter taste of its
   salt in the wind) that is at the center of a watershed that encompases the
   entire surface of the planet. Even in its spent and depleted state, Skâr is
   still a treasure of geological resources. The people burn "fossil fuels" they
   dig or pump out of the ground. There's a city there, on the piratical shore
   of the Last Dead Lake, that uses the dead water as an enormous battery with
   two towers or rather towering spikes on the side of the planet named Anode
   and Cathode. The circumference of the dead sea is a spaceport, here the
   shrieking spaceplanes needing long landing strips come to land ... and silent
   and majestic the slow lighters descend, glinting far overhead, lit by the
   pitiless sun of Skâr, or by the desolate lava red of Skâr's defunctive
   sunsets, ships varying in size from small drone vehicles to craft the size of
   mountains, buouyed and weightless with gravity polarization technology. When
   these land they kiss the ground. There's berth for every manner of vessel at
   the Last Dead Lake. 

   The people of Yrth however do not stick to Yrth. They carry their lifeways to
   other planets, other stellar systems, they lead their clawed, mutant,
   flesheating armored horses into the bays of frigates, they drive their
   roaring reeking warmachines in too, and they light and disboat on alien soil,
   their faces or their helmet viewplates blown by alien winds, screaming their
   huge sound and violence and rapacity at the greater universe, and when the
   used up butt-ends of these expeditions return to their frigates they bear
   away all they can carry.

   /How would I know about such things?/ That's what I tell people. But now you
   know.






   ========

* asdf
